/**
 * Which essences can be used on a given item, and what each would do there.
 * Data comes from essences.json (generated by scripts/gen-essences.mjs from
 * poe2db — re-run after game patches).
 */
import data from './essences.json'
import { craftedCapNote, type CraftedSlots } from './craftedSlots'
import { conflictingMod, type ItemMod } from './conflict'
import { modForClass, type RawCraftCurrency, type RawCraftMod } from './targets'

export type EssenceTier = 'lesser' | 'normal' | 'greater' | 'perfect' | 'corrupted'

export interface EssenceForItem {
  /** Base-item metadata id, e.g. "CurrencyLesserEssenceLife". */
  id: string
  name: string
  tier: EssenceTier
  /** Family shared across tiers ("the Body", "Flames") for visual grouping. */
  family: string
  /** The guaranteed mod this essence gives on the asked-about item class. */
  modText: string
  /**
   * Display text of the existing item mod that blocks this essence by sharing
   * the guaranteed mod's group (issue #72), or null when nothing conflicts.
   * Set for both paths — a Perfect/corrupted essence that augments a Rare and a
   * Greater essence that upgrades a Magic item both stamp a guaranteed mod the
   * game refuses when an existing mod already holds that group (e.g. Greater
   * Essence of Opulence on a Magic item that already has a Rarity suffix). The
   * essence stays listed (not hidden) so the UI can show it greyed with reason.
   */
  blockedBy: string | null
  /** Bundled art filename (renderer asset under assets/essences/), if any. */
  icon: string | null
}

export interface EssenceAdvice {
  /** Essences usable on this item (class + rarity both pass), display order. */
  applicable: EssenceForItem[]
  /**
   * Rarity context for the header line: how the listed essences apply, or
   * why the list is empty. Null when essences plain don't exist for the class.
   */
  note: string | null
}

type RawEssence = RawCraftCurrency

function tierOf(e: RawEssence): EssenceTier {
  if (e.id.includes('CorruptedEssence')) return 'corrupted'
  if (e.name.startsWith('Lesser ')) return 'lesser'
  if (e.name.startsWith('Greater ')) return 'greater'
  if (e.name.startsWith('Perfect ')) return 'perfect'
  return 'normal'
}

/** "Greater Essence of the Body" -> "the Body"; corrupted keep full suffix. */
function familyOf(name: string): string {
  return name.replace(/^(Lesser|Greater|Perfect) /, '').replace(/^Essence of /, '')
}

/** Tier order within a family: weakest first, rare-only tiers last. */
const TIER_ORDER: Record<EssenceTier, number> = {
  lesser: 0,
  normal: 1,
  greater: 2,
  perfect: 3,
  corrupted: 4
}

// The source page also lists Verisium Alloys (essence-like rare-item
// currencies) — they're filtered out here and handled by alloys.ts (#51).
// Lesser/regular tiers are dropped too: by the time someone price-checks
// with a crafting eye, only Greater/Perfect (and corrupted) are worth using.
const ESSENCES = (data.essences as RawEssence[])
  .filter((e) => e.name.includes('Essence'))
  .map((e) => ({
    ...e,
    tier: tierOf(e),
    family: familyOf(e.name),
    /** True for "Removes a random modifier and augments a Rare item…". */
    rareOnly: e.behavior.startsWith('Removes')
  }))
  .filter((e) => e.tier === 'greater' || e.tier === 'perfect' || e.tier === 'corrupted')

/** The guaranteed mod this essence gives on an item class, or null if none. */
function modFor(e: (typeof ESSENCES)[number], itemClass: string): RawCraftMod | null {
  return modForClass(e.mods, itemClass)
}

export function essencesForItem(
  itemClass: string,
  rarity: string,
  crafted?: CraftedSlots,
  /** The item's existing explicit mods + groups, for the group-conflict gate
   *  (#72). Omitted (or empty) disables the gate — every essence lists unblocked. */
  existing?: ItemMod[]
): EssenceAdvice {
  const onClass = ESSENCES.flatMap((e) => {
    const mod = modFor(e, itemClass)
    return mod === null ? [] : [{ essence: e, mod }]
  })

  if (onClass.length === 0) {
    return { applicable: [], note: null }
  }

  let usable: typeof onClass
  let note: string
  switch (rarity) {
    case 'Magic':
      usable = onClass.filter((x) => !x.essence.rareOnly)
      note = 'Magic item — a Greater essence upgrades it to Rare with the listed modifier'
      break
    case 'Rare':
      // Perfect & corrupted essences augment the Rare with a guaranteed mod in
      // its single crafted slot; if that slot is already full (cap reached) the
      // game blocks them, so drop them with a reason rather than list dead ends.
      if (crafted && crafted.used >= crafted.cap) {
        return { applicable: [], note: craftedCapNote(crafted, 'Perfect & corrupted Essences') }
      }
      usable = onClass.filter((x) => x.essence.rareOnly)
      note = 'Rare item — only Perfect & corrupted essences apply (replace a random modifier)'
      break
    case 'Normal':
      usable = onClass.filter((x) => !x.essence.rareOnly)
      note = 'Normal item — needs a Transmute first; Greater essences then apply at Magic'
      break
    default:
      // Unique, gems, currency… nothing applies, but the class has essences.
      return { applicable: [], note: `Essences cannot be used on ${rarity} items` }
  }

  const applicable = usable
    .map(({ essence, mod }) => ({
      id: essence.id,
      name: essence.name,
      tier: essence.tier,
      family: essence.family,
      modText: mod.text,
      // The guaranteed mod is refused when an existing mod already holds its
      // group (#72). Applies to both the Magic→Rare and augment-a-Rare paths.
      blockedBy: existing ? (conflictingMod(mod.groups, existing)?.label ?? null) : null,
      icon: essence.icon ?? null
    }))
    .sort(
      (a, b) =>
        a.family.localeCompare(b.family) || TIER_ORDER[a.tier] - TIER_ORDER[b.tier]
    )

  return { applicable, note }
}
