/**
 * Which essences can be used on a given item, and what each would do there.
 * Data comes from essences.json (generated by scripts/gen-essences.mjs from
 * poe2db — re-run after game patches).
 */
import data from './essences.json'
import type { CraftedSlots } from './craftedSlots'

export type EssenceTier = 'lesser' | 'normal' | 'greater' | 'perfect' | 'corrupted'

export interface EssenceForItem {
  /** Base-item metadata id, e.g. "CurrencyLesserEssenceLife". */
  id: string
  name: string
  tier: EssenceTier
  /** Family shared across tiers ("the Body", "Flames") for visual grouping. */
  family: string
  /** The guaranteed mod this essence gives on the asked-about item class. */
  modText: string
  /** Bundled art filename (renderer asset under assets/essences/), if any. */
  icon: string | null
}

export interface EssenceAdvice {
  /** Essences usable on this item (class + rarity both pass), display order. */
  applicable: EssenceForItem[]
  /**
   * Rarity context for the header line: how the listed essences apply, or
   * why the list is empty. Null when essences plain don't exist for the class.
   */
  note: string | null
}

/**
 * poe2db target keyword -> clipboard "Item Class:" values (the vocabulary of
 * PreparedQuery.itemClass). Keep in sync with the "Target tokens" output of
 * gen-essences.mjs. Classes not in PoE2 yet (claws, daggers…) are omitted.
 */
const MELEE_ONE_HAND = ['One Hand Maces', 'Spears', 'Flails']
const MELEE_TWO_HAND = ['Two Hand Maces', 'Quarterstaves']
const MELEE = [...MELEE_ONE_HAND, ...MELEE_TWO_HAND]
const RANGED = ['Bows', 'Crossbows']
const CASTER = ['Wands', 'Staves', 'Sceptres']
const MARTIAL = [...MELEE, ...RANGED]
const WEAPONS = [...MARTIAL, ...CASTER]
const ARMOUR = ['Body Armours', 'Helmets', 'Gloves', 'Boots', 'Shields', 'Bucklers', 'Foci']
const JEWELLERY = ['Rings', 'Amulets']
const EQUIPMENT = [...WEAPONS, ...ARMOUR, ...JEWELLERY, 'Belts', 'Quivers']

const CLASSES_BY_TARGET: Record<string, string[]> = {
  Equipment: EQUIPMENT,
  Any: EQUIPMENT,
  Weapons: WEAPONS,
  'Martial Weapon': MARTIAL,
  'Melee Weapon': MELEE,
  'One Handed Melee Weapon': MELEE_ONE_HAND,
  'Two Handed Melee Weapon': MELEE_TWO_HAND,
  'Caster Weapon': CASTER,
  Mace: ['One Hand Maces', 'Two Hand Maces'],
  Bow: ['Bows'],
  Crossbow: ['Crossbows'],
  Quarterstaff: ['Quarterstaves'],
  Spear: ['Spears'],
  Wand: ['Wands'],
  Staff: ['Staves'],
  Sceptre: ['Sceptres'],
  Armour: ARMOUR,
  'Body Armour': ['Body Armours'],
  Helmet: ['Helmets'],
  Gloves: ['Gloves'],
  Boots: ['Boots'],
  Shield: ['Shields', 'Bucklers'],
  Focus: ['Foci'],
  Quiver: ['Quivers'],
  Jewellery: JEWELLERY,
  Ring: ['Rings'],
  Amulet: ['Amulets'],
  Belt: ['Belts'],
  Talisman: ['Talismans']
}

interface RawEssence {
  id: string
  name: string
  behavior: string
  mods: Array<{ targets: string[]; text: string }>
  icon?: string
}

function tierOf(e: RawEssence): EssenceTier {
  if (e.id.includes('CorruptedEssence')) return 'corrupted'
  if (e.name.startsWith('Lesser ')) return 'lesser'
  if (e.name.startsWith('Greater ')) return 'greater'
  if (e.name.startsWith('Perfect ')) return 'perfect'
  return 'normal'
}

/** "Greater Essence of the Body" -> "the Body"; corrupted keep full suffix. */
function familyOf(name: string): string {
  return name.replace(/^(Lesser|Greater|Perfect) /, '').replace(/^Essence of /, '')
}

/** Tier order within a family: weakest first, rare-only tiers last. */
const TIER_ORDER: Record<EssenceTier, number> = {
  lesser: 0,
  normal: 1,
  greater: 2,
  perfect: 3,
  corrupted: 4
}

// The source page also lists Verisium Alloys (essence-like rare-item
// currencies) — kept in the JSON for a future tab, out of scope here.
// Lesser/regular tiers are dropped too: by the time someone price-checks
// with a crafting eye, only Greater/Perfect (and corrupted) are worth using.
const ESSENCES = (data.essences as RawEssence[])
  .filter((e) => e.name.includes('Essence'))
  .map((e) => ({
    ...e,
    tier: tierOf(e),
    family: familyOf(e.name),
    /** True for "Removes a random modifier and augments a Rare item…". */
    rareOnly: e.behavior.startsWith('Removes')
  }))
  .filter((e) => e.tier === 'greater' || e.tier === 'perfect' || e.tier === 'corrupted')

function modTextFor(e: (typeof ESSENCES)[number], itemClass: string): string | null {
  for (const mod of e.mods) {
    for (const target of mod.targets) {
      if (CLASSES_BY_TARGET[target]?.includes(itemClass)) return mod.text
    }
  }
  return null
}

/** Reason line shown when a Rare's crafted slot(s) are full (issue #24). */
function craftedCapNote(crafted: CraftedSlots): string {
  const mods = crafted.used === 1 ? 'a crafted modifier' : `${crafted.used} crafted modifiers`
  const reason =
    crafted.cap > 1
      ? `the crafted-mod cap (${crafted.cap}, raised by Astrid's Creativity) is full`
      : 'an item holds only one crafted modifier'
  return `This item already has ${mods} — Perfect & corrupted Essences can't be applied (${reason}).`
}

export function essencesForItem(
  itemClass: string,
  rarity: string,
  crafted?: CraftedSlots
): EssenceAdvice {
  const onClass = ESSENCES.flatMap((e) => {
    const modText = modTextFor(e, itemClass)
    return modText === null ? [] : [{ essence: e, modText }]
  })

  if (onClass.length === 0) {
    return { applicable: [], note: null }
  }

  let usable: typeof onClass
  let note: string
  switch (rarity) {
    case 'Magic':
      usable = onClass.filter((x) => !x.essence.rareOnly)
      note = 'Magic item — a Greater essence upgrades it to Rare with the listed modifier'
      break
    case 'Rare':
      // Perfect & corrupted essences augment the Rare with a guaranteed mod in
      // its single crafted slot; if that slot is already full (cap reached) the
      // game blocks them, so drop them with a reason rather than list dead ends.
      if (crafted && crafted.used >= crafted.cap) {
        return { applicable: [], note: craftedCapNote(crafted) }
      }
      usable = onClass.filter((x) => x.essence.rareOnly)
      note = 'Rare item — only Perfect & corrupted essences apply (replace a random modifier)'
      break
    case 'Normal':
      usable = onClass.filter((x) => !x.essence.rareOnly)
      note = 'Normal item — needs a Transmute first; Greater essences then apply at Magic'
      break
    default:
      // Unique, gems, currency… nothing applies, but the class has essences.
      return { applicable: [], note: `Essences cannot be used on ${rarity} items` }
  }

  const applicable = usable
    .map(({ essence, modText }) => ({
      id: essence.id,
      name: essence.name,
      tier: essence.tier,
      family: essence.family,
      modText,
      icon: essence.icon ?? null
    }))
    .sort(
      (a, b) =>
        a.family.localeCompare(b.family) || TIER_ORDER[a.tier] - TIER_ORDER[b.tier]
    )

  return { applicable, note }
}
