/**
 * Which Liquid Emotions can be applied to a given jewel, and what guaranteed
 * crafted mod each would give there (issue #48). Liquids are the essence-like
 * jewel-crafting use of Delirium's Liquid Emotions: applied to a Rare jewel
 * they remove a random modifier and augment it with a guaranteed crafted mod.
 *
 * Data comes from liquids.json (generated by scripts/gen-liquids.mjs from
 * poe2db — re-run after game patches). The mod a liquid grants depends on the
 * jewel's GEM base (Ruby/Sapphire/Emerald/Diamond) and on whether the jewel is
 * Basic or Time-Lost, so this keys off the parsed base type, not the item class
 * (every jewel is `Item Class: Jewels`).
 */
import data from './liquids.json'
import { craftedCapNote, type CraftedSlots } from './craftedSlots'
import { conflictingMod, type ItemMod } from './conflict'

/** The four jewel gem bases; a base type is the gem, optionally `Time-Lost `. */
const GEMS = ['Ruby', 'Sapphire', 'Emerald', 'Diamond']
const TIME_LOST = 'Time-Lost '
// Diamond is the wildcard jewel: it can host the attribute (Ruby/Sapphire/
// Emerald) mods, so a liquid applied to it rolls a RANDOM one of all its
// variants — unlike the attribute jewels, which only ever take their own column.
const DIAMOND = 'Diamond'

export interface LiquidMod {
  affix: 'prefix' | 'suffix'
  /** The guaranteed mod text for the hovered jewel's gem. */
  text: string
  /**
   * Display text of the jewel mod that blocks this outcome by sharing its group
   * (issue #78), or null when nothing conflicts. A liquid removes-and-augments,
   * so the game refuses it when the jewel already holds the guaranteed mod's
   * group. Per-outcome: a "rolls one of" liquid (Diamond wildcard, Potent
   * prefix/suffix) can have some outcomes blocked and others not.
   */
  blockedBy: string | null
}

export interface LiquidForItem {
  id: string
  name: string
  /** Potent (unique-effect) liquids — visually distinguished from base ones. */
  potent: boolean
  /**
   * Possible mod(s) this liquid grants on the hovered jewel — a liquid always
   * adds exactly one, so >1 entry means it rolls a random one of them (a Diamond
   * jewel rolls across attribute variants when the liquid has no Diamond column;
   * Potent liquids offer a prefix OR suffix).
   */
  mods: LiquidMod[]
  /** Bundled art filename (renderer asset under assets/liquids/), if any. */
  icon: string | null
}

export interface LiquidAdvice {
  /** Liquids usable on this jewel, display order. */
  applicable: LiquidForItem[]
  /**
   * Context for the header line: how the listed liquids apply, or why the list
   * is empty. Null when the item isn't a jewel we have liquids for.
   */
  note: string | null
}

interface RawLiquidMod {
  gem: string
  affix: string
  text: string
  /** Mod-group(s) of this guaranteed mod (joined from the 'misc'-domain jewel
   *  mods by gen-liquids.mjs). Empty for Time-Lost passive-grant mods, which
   *  aren't in the upstream dump — those never block. */
  groups: string[]
}
interface RawLiquid {
  id: string
  name: string
  target: 'basic' | 'time-lost'
  potent: boolean
  mods: RawLiquidMod[]
  icon?: string
}

const LIQUIDS = data.liquids as RawLiquid[]

/** Split a jewel base type into its target family and gem, or null if it isn't
 *  one of the four gem jewels (basic or Time-Lost) we handle. */
function jewelKind(baseType: string): { target: 'basic' | 'time-lost'; gem: string } | null {
  const timeLost = baseType.startsWith(TIME_LOST)
  const gem = timeLost ? baseType.slice(TIME_LOST.length) : baseType
  if (!GEMS.includes(gem)) return null
  return { target: timeLost ? 'time-lost' : 'basic', gem }
}

export function liquidsForItem(
  itemClass: string,
  baseType: string,
  rarity: string,
  crafted?: CraftedSlots,
  /** The jewel's existing mods + groups, for the group-conflict gate (#78).
   *  Omitted (or empty) disables it — every outcome lists unblocked. */
  existing?: ItemMod[]
): LiquidAdvice {
  if (itemClass !== 'Jewels') return { applicable: [], note: null }
  const kind = jewelKind(baseType)
  if (!kind) return { applicable: [], note: null }

  switch (rarity) {
    case 'Rare':
      break
    case 'Magic':
    case 'Normal':
      // Liquids remove-and-augment, so they need a Rare jewel with mods to
      // replace (they don't upgrade rarity the way Greater essences do).
      return { applicable: [], note: 'Liquids only apply to Rare jewels' }
    default:
      return { applicable: [], note: `Liquids cannot be used on ${rarity} jewels` }
  }

  // A liquid augments with a crafted mod in the jewel's single crafted slot; if
  // that slot is full the game blocks it (issue #24, same as corrupted essences).
  if (crafted && crafted.used >= crafted.cap) {
    return { applicable: [], note: craftedCapNote(crafted, 'Liquid Emotions') }
  }

  const applicable = LIQUIDS.flatMap((l) => {
    if (l.target !== kind.target) return []
    // An attribute gem gets only its own column. Diamond takes its own column
    // when the liquid has one (e.g. Isolation → chaos res only); lacking a
    // Diamond line it's the wildcard and rolls any attribute variant. Either
    // way a liquid adds exactly one mod, so >1 entry = a random "rolls one of"
    // (also how Potent liquids offer a prefix OR suffix).
    let lines: RawLiquidMod[]
    if (kind.gem === DIAMOND) {
      const diamond = l.mods.filter((m) => m.gem === DIAMOND)
      lines = diamond.length > 0 ? diamond : l.mods
    } else {
      lines = l.mods.filter((m) => m.gem === kind.gem)
    }
    const seen = new Set<string>()
    const mods: LiquidMod[] = []
    for (const m of lines) {
      const key = `${m.affix}|${m.text}`
      if (seen.has(key)) continue
      seen.add(key)
      const blocker = existing ? conflictingMod(m.groups, existing) : null
      mods.push({
        affix: m.affix as 'prefix' | 'suffix',
        text: m.text,
        blockedBy: blocker?.label ?? null
      })
    }
    if (mods.length === 0) return []
    return [{ id: l.id, name: l.name, potent: l.potent, mods, icon: l.icon ?? null }]
  }).sort(
    (a, b) => Number(a.potent) - Number(b.potent) || a.name.localeCompare(b.name)
  )

  const note =
    kind.target === 'time-lost'
      ? 'Time-Lost jewel — Ancient liquids replace a random modifier with the listed crafted one'
      : 'Rare jewel — a liquid replaces a random modifier with the listed crafted one'

  return { applicable, note }
}
